### ISSUE TITLE
Distibution is not an archive

### ISSUE THREAD

**Issue by profray** [GCuser99/FFmpeg-vba#1]
Hi, I dowloaded the most recent distribution file (.zip file) and tried to unzip and I was told it was not an archive file
Where is the distribution file?
Thanks

**Comment by GCuser99** [comment]
Hi @profray - what OS are you running? I just downloaded on my Windows 11 machine and was able to unzip it with Windows Explorer...

**Comment by profray** [comment]
I must be doing something very dumb. But here is a screen capture of what I am trying to do. I know it must be something really simple. Apologies in advance. 

https://user-images.githubusercontent.com/26842429/235877839-faa32749-8765-4b0d-832e-d48264ae3cd2.mp4

System is Windows 10,  I have tried with 7zip and windows

**Comment by GCuser99** [comment]
Thanks for the video - instead of right-mouse-button click save-link-as, click once on the zip file ffmpeg-vba_v0.4.zip in the dist folder. Then you should see a download (down arrow) button on the right side - click on that!

![image](https://user-images.githubusercontent.com/26237126/235925069-5ed2f8c2-332e-4266-962f-ec6d992dd996.png)

**Comment by GCuser99** [comment]
@profray, I'll close this one assuming that you figured it out...
